export const WORKSPACE_INVITE_TOKEN_LENGTH = 24;

export const PERSON_NAME_MIN_CHARS = 2;
export const PERSON_NAME_MAX_CHARS = 50;

export const WORKSPACE_NAME_MIN_CHARS = 3;
export const WORKSPACE_NAME_MAX_CHARS = 50;
export const WORKSPACE_DESCRIPTION_MAX_CHARS = 250;

export const OBJECTIVE_NAME_MIN_CHARS = 3;
export const OBJECTIVE_NAME_MAX_CHARS = 50;
export const OBJECTIVE_DESCRIPTION_MAX_CHARS = 250;
