export enum ApiErrorCode {
  SERVER_ERROR = '0',
  INVALID_PAYLOAD = '1',
  EMAIL_ALREADY_EXISTS = '2',
  WORKSPACE_INVITE_ALREADY_USED = '3',
  WORKSPACE_INVITE_EXPIRED = '4',
  WORKSPACE_INVITE_EXISTING_USER = '5',
  NOT_FOUND_WORKSPACE_INVITE_TOKEN = '6',
  TASK_CLOSED = '7',
}
